### ISSUE TITLE
Add Open Telemetry collection and visualization

### ISSUE THREAD

**Issue by michaellperry** [jinaga/university-system#1]
Here is the updated `docker-compose.yml` file with Jaeger added:

```yaml
name: university-mesh

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.15
    platform: "linux/amd64"
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  back-end-replicator:
    image: jinaga/jinaga-replicator:latest
    container_name: back-end-replicator
    ports:
      - "8080:8080"
    volumes:
      - ./policies:/var/lib/replicator/policies:ro
      - ./authentication:/var/lib/replicator/authentication:ro
      - ./subscriptions:/var/lib/replicator/subscriptions:ro

  importer:
    build:
      context: ../src
      dockerfile: University.Importer/Dockerfile
    environment:
      - REPLICATOR_URL=http://back-end-replicator:8080/jinaga
      - ENVIRONMENT_PUBLIC_KEY=default-public-key
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - back-end-replicator
      - otel-collector

  indexer:
    build:
      context: ../src
      dockerfile: University.Indexer/Dockerfile
    environment:
      - REPLICATOR_URL=http://back-end-replicator:8080/jinaga
      - ENVIRONMENT_PUBLIC_KEY=default-public-key
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - back-end-replicator
      - elasticsearch
      - otel-collector

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    ports:
      - "4317:4317"
      - "55680:55680"
    volumes:
      - ./otel-collector-config.yml:/otel-collector-config.yml
    command: ["--config=/otel-collector-config.yml"]

volumes:
  esdata:
```

In this configuration:
- Jaeger is added as a new service, exposing its UI on port 16686 and the UDP receiver on port 6831.
- The Open Telemetry Collector is configured to export traces to Jaeger.
